<?php

namespace PedroGuerra\DeveloperTest\Block\Slider;

class HomeSlider extends \Magento\Framework\View\Element\Template
{

    const ITEM_AMOUNT = 10;

    const PATH_RANDOM_IMAGE = 'https://picsum.photos/200/300?image=%d';

    const XML_PATH_ACTIVE = 'general/developtest/active';

    /**
     * @var \Magento\Framework\App\Config\ScopeConfigInterface
     */
    protected $scopeConfig;

    public function __construct(
        \Magento\Framework\View\Element\Template\Context $context,
        \Magento\Framework\App\Config\ScopeConfigInterface $scopeConfig,
        array $data = []
    )
    {
        $this->scopeConfig = $scopeConfig;
        parent::__construct($context, $data);
    }

    /**
     * @return int
     */
    public function getItemAmout()
    {
        return self::ITEM_AMOUNT;
    }

    /**
     * @return string
     */
    public function getImageUrl($id = 0)
    {
        return sprintf(self::PATH_RANDOM_IMAGE, $id);
    }

    public function getIsActive(){
        $isActive = $this->scopeConfig->getValue(
            self::XML_PATH_ACTIVE,
            \Magento\Store\Model\ScopeInterface::SCOPE_STORE
        );
        return $isActive ? true : false;
    }

    public function _toHtml()
    {
        if(!$this->getIsActive()){
            return '';
        }
        return parent::_toHtml(); // TODO: Change the autogenerated stub
    }
}
